/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author luan-
 */
public class Interface extends javax.swing.JFrame {
    public static boolean aberto;
    
    
    
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpInterface = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadCli = new javax.swing.JMenu();
        menuCad = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSaldCli = new javax.swing.JMenuItem();
        menuSaldAgen = new javax.swing.JMenuItem();
        menuSaldBanc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuTransfTED = new javax.swing.JMenuItem();
        menuTransfPIX = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuExtrSaq = new javax.swing.JMenuItem();
        menuExtrDep = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bancario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jdpInterfaceLayout = new javax.swing.GroupLayout(jdpInterface);
        jdpInterface.setLayout(jdpInterfaceLayout);
        jdpInterfaceLayout.setHorizontalGroup(
            jdpInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jdpInterfaceLayout.setVerticalGroup(
            jdpInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jmCadCli.setText("Clientes");

        menuCad.setText("CadastrarCliente");
        menuCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadActionPerformed(evt);
            }
        });
        jmCadCli.add(menuCad);

        jMenuBar1.add(jmCadCli);

        jMenu2.setText("Operações");

        menuSaldCli.setText("Ver saldo de um cliente em uma agência");
        menuSaldCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaldCliActionPerformed(evt);
            }
        });
        jMenu2.add(menuSaldCli);

        menuSaldAgen.setText("Ver o valor total aplicado em uma agência");
        menuSaldAgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaldAgenActionPerformed(evt);
            }
        });
        jMenu2.add(menuSaldAgen);

        menuSaldBanc.setText("Ver valor total aplicado no banco");
        menuSaldBanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaldBancActionPerformed(evt);
            }
        });
        jMenu2.add(menuSaldBanc);

        jMenu3.setText("Fazer transferências entre clientes");

        menuTransfTED.setText("Via TED");
        menuTransfTED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransfTEDActionPerformed(evt);
            }
        });
        jMenu3.add(menuTransfTED);

        menuTransfPIX.setText("Via PIX");
        menuTransfPIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransfPIXActionPerformed(evt);
            }
        });
        jMenu3.add(menuTransfPIX);

        jMenu2.add(jMenu3);

        jMenu1.setText("Extrato detalhado");

        menuExtrSaq.setText("Realizar Saque");
        menuExtrSaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExtrSaqActionPerformed(evt);
            }
        });
        jMenu1.add(menuExtrSaq);

        menuExtrDep.setText("Realizar Deposito");
        menuExtrDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExtrDepActionPerformed(evt);
            }
        });
        jMenu1.add(menuExtrDep);

        jMenu2.add(jMenu1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpInterface)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpInterface)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        Interface.aberto=false;
    }//GEN-LAST:event_formWindowOpened

    private void menuCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadActionPerformed
        //Conectar a Interface Interna a Interface Externa
        if (aberto==false) {
            Cadastro obj = new Cadastro();
            jdpInterface.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_menuCadActionPerformed

    private void menuSaldCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaldCliActionPerformed
        if (aberto==false) {
            SaldoCliente obj = new SaldoCliente();
            jdpInterface.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_menuSaldCliActionPerformed

    private void menuSaldAgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaldAgenActionPerformed
        if (aberto==false) {
            SaldoAgencia obj = new SaldoAgencia();
            jdpInterface.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_menuSaldAgenActionPerformed

    private void menuSaldBancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaldBancActionPerformed
        if (aberto==false) {
            SaldoBanco obj = new SaldoBanco();
            jdpInterface.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_menuSaldBancActionPerformed

    private void menuTransfTEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransfTEDActionPerformed
        if (aberto==false) {
            TransfTED obj = new TransfTED();
            jdpInterface.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_menuTransfTEDActionPerformed

    private void menuTransfPIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransfPIXActionPerformed
        if (aberto==false) {
            TransfPIX obj = new TransfPIX();
            jdpInterface.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_menuTransfPIXActionPerformed

    private void menuExtrSaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExtrSaqActionPerformed
        if (aberto==false) {
            ExtratoSaque obj = new ExtratoSaque();
            jdpInterface.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_menuExtrSaqActionPerformed

    private void menuExtrDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExtrDepActionPerformed
        if (aberto==false) {
            ExtratoDeposito obj = new ExtratoDeposito();
            jdpInterface.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_menuExtrDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpInterface;
    private javax.swing.JMenu jmCadCli;
    private javax.swing.JMenuItem menuCad;
    private javax.swing.JMenuItem menuExtrDep;
    private javax.swing.JMenuItem menuExtrSaq;
    private javax.swing.JMenuItem menuSaldAgen;
    private javax.swing.JMenuItem menuSaldBanc;
    private javax.swing.JMenuItem menuSaldCli;
    private javax.swing.JMenuItem menuTransfPIX;
    private javax.swing.JMenuItem menuTransfTED;
    // End of variables declaration//GEN-END:variables
}
